env:
  es2021: true
  jest/globals: true
  node: true
extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides:
  -
    files: ['*.spec.ts']
    plugins: ['jest']
    extends: ['plugin:jest/all']
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project: './tsconfig.json'
  sourceType: module
settings:
  import/resolver:
    typescript: {}
rules:
  import/no-default-export: 'error'
