env:
  es2021: true
  node: true
extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver:
    typescript: {}
rules:
  import/no-default-export: 'error'
